version: '3'
services:
  app1:
    container_name: app1
    build: app1/
    ports:
      - 3000:3000
    command: ["npm", "start"]
  app2:
    container_name: app2
    build: app2/
    command: ["npm", "start"]
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - "rabbitmq"
  app3:
    container_name: app3
    build: app3/
    command: ["./main"]
    restart: on-failure
    depends_on:
      - "rabbitmq"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
